# README


**Project Title:**  

**Tutorial section: TT5L**

**Group08**

<div align="left">
    
| | Student ID     | Student Name                | Contribution | 
|--:|:-------------|:----------------------------|-------------:|
| 1 | 242UC244T5  | MUHAMMAD NUR AIZAD BIN MURTADHA               | %          | 
| 2 | Student_ID2  | WONG JIE KIT               | %          | 
| 3 | Student_ID3  | YUVENDAR A/L MARAN               | %          | 
| 4 | Student_ID4  | ZIAD ALDARKHBANI               | %          | 

</div>

Note: Marks may vary among group members based on individual contributions. Ensure all members agree on the contribution percentages listed here.

**YouTube link:**  
Please note that the examiner will not notify you if your video link is unavailable, inaccessible, or incorrectly provided. It is the responsibility of the group to ensure that the video link is fully functional and accessible at the time of assessment. Failure to provide a valid and working link will result in a score of zero (0) marks for the presentation component.

**Dataset Title:**\
Traffic Accidents\
**Source & Link:** (e.g., Kaggle / UCI / Data.gov / Google Dataset Search — provide the dataset page URL)\
https://www.kaggle.com/datasets/oktayrdeki/traffic-accidents \
**Download instructions:** If the dataset requires sign-in (e.g., Kaggle), document the exact steps here\
1. 
2.    
**Brief Description (2–4 sentences):**   
The dataset is about traffic accidents. It takes into account causes of traffic accidents, time period of traffic accidents and injury outcomes.

**How to Run (if required, 1–3 steps):**  
  Instructions to run the notebook, including how to place the dataset files.

## 1. Introduction & Problem Statement
- What is the main objective of this analysis?
- What key questions/hypotheses will you explore?
- Why is this dataset suitable for these questions?
- All citations must be in listed in APA style.

The main objective of this analysis is to identify patterns of traffic accidents regarding crash timing, environmental factors, and injuries. Through this analysis, we can help support traffic management and improve road safety.

Key questions/hypothesis that will be explored through this analysis include:-
1. Can most severe injury outcome be predicted based on crash hour, crash day of the week, weather conditions, lighting conditions, and roadway surface conditions?
2. Can total number of injuries be predicted based on crash hour, crash day of the week, number of vehicles involved, and trafficway type?
3. What groups of traffic accidents can be identified based on weather conditions, lighting conditions, roadway surface conditions, and primary contributory causes?
4. What is the yearly trend in the number of traffic accidents over time?

This dataset is suitable for these questions because it is rich with variables related to traffic accidents, such as, environmental factors, crash timing, and crash outcome. Not only that, this dataset has both numerical and categorical data which allows the application of multiple distinct techniques or algorithms.

## 2. Data Source & Understanding
- **Description:** Features/columns, size, time span, units
- **Limitations:** Coverage, missingness, sampling bias, known caveats

**Features/columns**
| Features/column | Units |
| --- | --- |
| crash_date | date and time |
| traffic_control_device | not applicable |
| weather_condition | not applicable |
| lighting_condition | not applicable |
| first_crash_type | not applicable |
| trafficway_type | not applicable |
| alignment | not applicable |
| roadway_surface_cond | not applicable |
| road_defect | not applicable |
| crash_type | not applicable |
| intersection_related_i | not applicable |
| damage | not applicable |
| prim_contributory_cause | not applicable |
| num_units | count |
| most_severe_injury | not applicable |
| injuries_total | count |
| injuries_fatal | count |
| injuries_incapacitating | count |
| injuries_non_incapacitating | count |
| injuries_reported_not_evident | count |
| injuries_no_indication | count |
| crash_hour | hour |
| crash_day_of_week | day |
| crash_month | month |


**Size**\
Rows: 209307
Columns: 24

**Time span**\
4th March 2013 - 18th January 2025

**Limitations**\
**Coverage**\
The dataset does not specify the location of the traffic accidents. This would make it harder for authorities to identify high-risk areas.\
**Missingness**

In [1]:
import numpy as np
import pandas as pd

accidents = pd.read_csv("traffic_accidents.csv")
print("Missingness")
print("------------------")
print(accidents.isnull().sum())

Missingness
------------------
crash_date                       0
traffic_control_device           0
weather_condition                0
lighting_condition               0
first_crash_type                 0
trafficway_type                  0
alignment                        0
roadway_surface_cond             0
road_defect                      0
crash_type                       0
intersection_related_i           0
damage                           0
prim_contributory_cause          0
num_units                        0
most_severe_injury               0
injuries_total                   0
injuries_fatal                   0
injuries_incapacitating          0
injuries_non_incapacitating      0
injuries_reported_not_evident    0
injuries_no_indication           0
crash_hour                       0
crash_day_of_week                0
crash_month                      0
dtype: int64

## 3. Initial Data Checks
- Shape, columns, dtypes
- Sample rows (head/tail)
- Basic summary statistics

In [2]:
#import numpy as np
#import pandas as pd

print("Shape:", accidents.shape, "\n")
print ("Columns:\n", accidents.columns, "\n")
print("Data Types:\n", accidents.dtypes, "\n")

Shape: (209306, 24)

Columns:
 Index(['crash_date', 'traffic_control_device', 'weather_condition',
       'lighting_condition', 'first_crash_type', 'trafficway_type',
       'alignment', 'roadway_surface_cond', 'road_defect', 'crash_type',
       'intersection_related_i', 'damage', 'prim_contributory_cause',
       'num_units', 'most_severe_injury', 'injuries_total', 'injuries_fatal',
       'injuries_incapacitating', 'injuries_non_incapacitating',
       'injuries_reported_not_evident', 'injuries_no_indication', 'crash_hour',
       'crash_day_of_week', 'crash_month'],
      dtype='object')

Data Types:
 crash_date                        object
traffic_control_device            object
weather_condition                 object
lighting_condition                object
first_crash_type                  object
trafficway_type                   object
alignment                         object
roadway_surface_cond              object
road_defect                       object
crash_type                        object
intersection_related_i            object
damage                            object
prim_contributory_cause           object
num_units                          int64
most_severe_injury                object
injuries_total                   float64
injuries_fatal                   float64
injuries_incapacitating          float64
injuries_non_incapacitating      float64
injuries_reported_not_evident    float64
injuries_no_indication           float64
crash_hour                         int64
crash_day_of_week                  int64
crash_month                        int64
dtype: object

In [3]:
accidents.head()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
0,07/29/2023 01:00:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,13,7,7
1,08/13/2023 12:11:00 AM,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0,1,8
2,12/09/2021 10:30:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,10,5,12
3,08/09/2023 07:55:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,5.0,0.0,0.0,5.0,0.0,0.0,19,4,8
4,08/19/2023 02:55:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,14,7,8

In [4]:
accidents.tail()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
209301,09/13/2023 01:08:00 PM,UNKNOWN,UNKNOWN,UNKNOWN,TURNING,FOUR WAY,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,13,4,9
209302,07/18/2023 02:10:00 PM,UNKNOWN,CLEAR,DAYLIGHT,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,14,3,7
209303,10/23/2019 01:32:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,PEDESTRIAN,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT ON GRADE,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,INCAPACITATING INJURY,2.0,0.0,2.0,0.0,0.0,0.0,13,4,10
209304,06/01/2020 03:23:00 PM,NO CONTROLS,CLEAR,DAYLIGHT,PEDESTRIAN,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,1.0,15,2,6
209305,12/16/2022 12:10:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,FOUR WAY,STRAIGHT AND LEVEL,WET,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,12,6,12

In [5]:
accidents.describe()

,num_units,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
count,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000,209306.000000
mean,2.063300,0.382717,0.001859,0.038102,0.221241,0.121516,2.244002,13.373047,4.144024,6.771822
std,0.396012,0.799720,0.047502,0.233964,0.614960,0.450865,1.241175,5.603830,1.966864,3.427593
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,9.000000,2.000000,4.000000
50%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,14.000000,4.000000,7.000000
75%,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,17.000000,6.000000,10.000000
max,11.000000,21.000000,3.000000,7.000000,21.000000,15.000000,49.000000,23.000000,7.000000,12.000000

## 4. Data Cleaning & Preprocessing
- Handle missing values (strategy and justification)
- Fix types (dates, categoricals, numerics)
- Remove/flag outliers
- Feature engineering (document purpose)
- Keep transformations transparent and reproducible

In [6]:
#FINDING DUPLICATES

#duplicates = accidents[accidents.duplicated(keep=False)]
#duplicates
accidents[accidents.duplicated()]

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
35141,08/31/2018 02:30:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,14,6,8
40269,07/17/2024 09:15:00 PM,TRAFFIC SIGNAL,CLEAR,DUSK,SIDESWIPE SAME DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,21,4,7
43671,02/14/2022 11:00:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,11,2,2
49142,05/19/2020 11:42:00 PM,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,3.0,0.0,0.0,3.0,0.0,1.0,23,3,5
51273,09/04/2023 05:59:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT ON GRADE,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,6.0,17,2,9
64682,09/06/2023 04:27:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,2.0,0.0,0.0,2.0,0.0,0.0,16,4,9
75198,02/14/2020 03:48:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,PEDESTRIAN,NOT DIVIDED,STRAIGHT AND LEVEL,SNOW OR SLUSH,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,INCAPACITATING INJURY,2.0,0.0,1.0,0.0,1.0,0.0,15,6,2
90336,08/13/2024 06:30:00 AM,NO CONTROLS,CLEAR,DAWN,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,5.0,6,3,8
117677,12/22/2018 01:40:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,13,7,12
123605,06/20/2022 07:30:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,19,2,6
124103,10/03/2023 10:20:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,10,3,10
129399,06/10/2019 09:38:00 PM,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE SAME DIRECTION,ONE-WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,21,2,6
139152,12/29/2020 05:30:00 PM,TRAFFIC SIGNAL,SNOW,"DARKNESS, LIGHTED ROAD",REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,SNOW OR SLUSH,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,17,3,12
151868,03/02/2022 04:30:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,16,4,3
152033,08/30/2018 03:30:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,15,5,8
153464,09/27/2018 08:30:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,8,5,9
156240,07/17/2023 04:05:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,16,2,7
159297,01/08/2020 12:20:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN (NOT RAISED),STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"REPORTED, NOT EVIDENT",1.0,0.0,0.0,0.0,1.0,1.0,12,4,1
174103,05/29/2020 06:00:00 PM,OTHER,CLEAR,DAYLIGHT,PEDALCYCLIST,DIVIDED - W/MEDIAN BARRIER,"CURVE, LEVEL",DRY,UNKNOWN,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,1.0,18,6,5
174897,02/25/2020 08:10:00 AM,TRAFFIC SIGNAL,SNOW,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,WET,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,2.0,0.0,0.0,2.0,0.0,3.0,8,3,2
174966,04/02/2018 01:00:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,13,2,4
175887,09/07/2018 03:00:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,TURNING,OTHER,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,15,6,9
180965,09/14/2023 04:00:00 PM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,16,5,9
185739,05/05/2023 04:12:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,FOUR WAY,STRAIGHT AND LEVEL,DRY,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,4.0,16,6,5
185959,12/10/2018 09:20:00 AM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,9,2,12
186709,08/11/2018 02:00:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,14,7,8
187095,11/03/2019 09:25:00 AM,STOP SIGN/FLASHER,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,UNKNOWN,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,0.0,9,1,11
194134,11/28/2016 02:30:00 PM,STOP SIGN/FLASHER,RAIN,DAYLIGHT,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,WET,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,14,2,11
196172,02/08/2020 03:40:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"REPORTED, NOT EVIDENT",1.0,0.0,0.0,0.0,1.0,2.0,15,7,2
197010,06/03/2023 06:10:00 PM,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,5.0,18,7,6
208986,07/11/2023 11:51:00 AM,TRAFFIC SIGNAL,CLOUDY/OVERCAST,DAYLIGHT,PEDALCYCLIST,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,1.0,0.0,0.0,1.0,0.0,1.0,11,3,7

In [7]:
accidents_clean = accidents.copy()
accidents_clean = accidents_clean.drop_duplicates()

In [8]:
accidents_clean.dtypes
#crash date change to date, 
#injuries total, fatal, incapacitating, non incapacitating, reported not evident, no indication change to int

crash_date                        object
traffic_control_device            object
weather_condition                 object
lighting_condition                object
first_crash_type                  object
trafficway_type                   object
alignment                         object
roadway_surface_cond              object
road_defect                       object
crash_type                        object
intersection_related_i            object
damage                            object
prim_contributory_cause           object
num_units                          int64
most_severe_injury                object
injuries_total                   float64
injuries_fatal                   float64
injuries_incapacitating          float64
injuries_non_incapacitating      float64
injuries_reported_not_evident    float64
injuries_no_indication           float64
crash_hour                         int64
crash_day_of_week                  int64
crash_month                        int64
dtype: object

In [9]:
#FIXING DATAYYPES
accidents_clean["crash_date"] = pd.to_datetime(accidents_clean["crash_date"])

C:\Users\User\AppData\Local\Temp\ipykernel_2704\2186815243.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  accidents_clean["crash_date"] = pd.to_datetime(accidents_clean["crash_date"])

In [10]:
accidents_clean.dtypes

crash_date                       datetime64[ns]
traffic_control_device                   object
weather_condition                        object
lighting_condition                       object
first_crash_type                         object
trafficway_type                          object
alignment                                object
roadway_surface_cond                     object
road_defect                              object
crash_type                               object
intersection_related_i                   object
damage                                   object
prim_contributory_cause                  object
num_units                                 int64
most_severe_injury                       object
injuries_total                          float64
injuries_fatal                          float64
injuries_incapacitating                 float64
injuries_non_incapacitating             float64
injuries_reported_not_evident           float64
injuries_no_indication                  float64
crash_hour                                int64
crash_day_of_week                         int64
crash_month                               int64
dtype: object

In [11]:
accidents_clean["crash_date"]

0        2023-07-29 13:00:00
1        2023-08-13 00:11:00
2        2021-12-09 10:30:00
3        2023-08-09 19:55:00
4        2023-08-19 14:55:00
                 ...
209301   2023-09-13 13:08:00
209302   2023-07-18 14:10:00
209303   2019-10-23 13:32:00
209304   2020-06-01 15:23:00
209305   2022-12-16 12:10:00
Name: crash_date, Length: 209275, dtype: datetime64[ns]

In [12]:
accidents_clean.head()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication,crash_hour,crash_day_of_week,crash_month
0,2023-07-29 13:00:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,13,7,7
1,2023-08-13 00:11:00,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0,0,1,8
2,2021-12-09 10:30:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,10,5,12
3,2023-08-09 19:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,NONINCAPACITATING INJURY,5.0,0.0,0.0,5.0,0.0,0.0,19,4,8
4,2023-08-19 14:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0,14,7,8

In [13]:
#accidents_copy.drop(columns=["crash_hour", "crash_day_of_week", "crash_month"])
#accidents_copy.head()
accidents_clean = accidents_clean.drop(columns=["crash_hour", "crash_day_of_week", "crash_month"])

In [14]:
accidents_clean.head()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,damage,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication
0,2023-07-29 13:00:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",UNABLE TO DETERMINE,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0
1,2023-08-13 00:11:00,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"OVER $1,500",IMPROPER TURNING/NO SIGNAL,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,2.0
2,2021-12-09 10:30:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",FOLLOWING TOO CLOSELY,3,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0
3,2023-08-09 19:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",UNABLE TO DETERMINE,2,NONINCAPACITATING INJURY,5.0,0.0,0.0,5.0,0.0,0.0
4,2023-08-19 14:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",DRIVING SKILLS/KNOWLEDGE/EXPERIENCE,2,NO INDICATION OF INJURY,0.0,0.0,0.0,0.0,0.0,3.0

In [15]:
accidents_clean["injuries_total"].unique()

array([ 0.,  5.,  2.,  1.,  3.,  4.,  6.,  7., 11., 17., 15.,  9.,  8.,
       10., 21., 19., 12., 16., 13.])

In [16]:
accidents_clean["injuries_fatal"].unique()

array([0., 1., 2., 3.])

In [17]:
accidents_clean["injuries_incapacitating"].unique()

array([0., 1., 2., 5., 3., 4., 6., 7.])

In [18]:
accidents_clean["injuries_non_incapacitating"].unique()

array([ 0.,  5.,  2.,  1.,  3.,  4.,  6.,  7., 10.,  8., 14.,  9., 19.,
       18., 21., 12., 11., 16., 13.])

In [19]:
accidents_clean["injuries_reported_not_evident"].unique()

array([ 0.,  1.,  2.,  3.,  5.,  4.,  6.,  8.,  7.,  9., 10., 15., 11.])

In [20]:
accidents_clean["injuries_no_indication"].unique()

array([ 3.,  2.,  0.,  1.,  4.,  5.,  6.,  8.,  7., 11., 10.,  9., 20.,
       12., 16., 13., 22., 18., 21., 42., 46., 26., 15., 17., 14., 27.,
       34., 19., 25., 36., 28., 32., 39., 29., 31., 37., 30., 49., 35.])

In [21]:
conversion = {"injuries_total" : int,
              "injuries_fatal" : int,
              "injuries_incapacitating" : int,
              "injuries_non_incapacitating" : int,
              "injuries_reported_not_evident" : int,
              "injuries_no_indication" : int}
accidents_clean = accidents_clean.astype(conversion)

In [22]:
accidents_clean.dtypes

crash_date                       datetime64[ns]
traffic_control_device                   object
weather_condition                        object
lighting_condition                       object
first_crash_type                         object
trafficway_type                          object
alignment                                object
roadway_surface_cond                     object
road_defect                              object
crash_type                               object
intersection_related_i                   object
damage                                   object
prim_contributory_cause                  object
num_units                                 int64
most_severe_injury                       object
injuries_total                            int64
injuries_fatal                            int64
injuries_incapacitating                   int64
injuries_non_incapacitating               int64
injuries_reported_not_evident             int64
injuries_no_indication                    int64
dtype: object

In [23]:
accidents_clean.head()

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,damage,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication
0,2023-07-29 13:00:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",UNABLE TO DETERMINE,2,NO INDICATION OF INJURY,0,0,0,0,0,3
1,2023-08-13 00:11:00,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",TURNING,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"OVER $1,500",IMPROPER TURNING/NO SIGNAL,2,NO INDICATION OF INJURY,0,0,0,0,0,2
2,2021-12-09 10:30:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",FOLLOWING TOO CLOSELY,3,NO INDICATION OF INJURY,0,0,0,0,0,3
3,2023-08-09 19:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,ANGLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",UNABLE TO DETERMINE,2,NONINCAPACITATING INJURY,5,0,0,5,0,0
4,2023-08-19 14:55:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,UNKNOWN,UNKNOWN,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",DRIVING SKILLS/KNOWLEDGE/EXPERIENCE,2,NO INDICATION OF INJURY,0,0,0,0,0,3

In [35]:
#FINDING OUTLIERS
def findingOutliers(column):
    Q1 = column.quantile(0.25)
    Q3 = column.quantile(0.75)
    IQR = Q3 - Q1

    lowerLimit = Q1 - 1.5*IQR
    upperLimit = Q3 + 1.5*IQR
    return (column < lowerLimit) | (column > upperLimit)

In [36]:
numerical_column = [ "num_units", "injuries_total", "injuries_fatal", "injuries_incapacitating",
                     "injuries_non_incapacitating", "injuries_reported_not_evident", "injuries_no_indication" ]

In [37]:
for col in numerical_column:
    outliers = findingOutliers(accidents_clean[col])
    print(col, ":", outliers.sum())

num_units : 19938
injuries_total : 5691
injuries_fatal : 351
injuries_incapacitating : 6633
injuries_non_incapacitating : 32994
injuries_reported_not_evident : 18684
injuries_no_indication : 16219

In [50]:
for col in numerical_column:
    values = accidents_clean[col].unique()
    print(col, ":", values)

#accidents_clean['num_units'].unique()

num_units : [ 2  3  1  4  5  6  8  7  9 10 11]
injuries_total : [ 0  5  2  1  3  4  6  7 11 17 15  9  8 10 21 19 12 16 13]
injuries_fatal : [0 1 2 3]
injuries_incapacitating : [0 1 2 5 3 4 6 7]
injuries_non_incapacitating : [ 0  5  2  1  3  4  6  7 10  8 14  9 19 18 21 12 11 16 13]
injuries_reported_not_evident : [ 0  1  2  3  5  4  6  8  7  9 10 15 11]
injuries_no_indication : [ 3  2  0  1  4  5  6  8  7 11 10  9 20 12 16 13 22 18 21 42 46 26 15 17
 14 27 34 19 25 36 28 32 39 29 31 37 30 49 35]

In [51]:
def extreme_outliers(col):
    lower = col.quantile(0.01)
    upper = col.quantile(0.99)
    return (col < lower) | (col > upper)

In [52]:
for col in numerical_column:
    outliers = findingOutliers(accidents_clean[col])
    print(col, ":", outliers.sum())

num_units : 19938
injuries_total : 5691
injuries_fatal : 351
injuries_incapacitating : 6633
injuries_non_incapacitating : 32994
injuries_reported_not_evident : 18684
injuries_no_indication : 16219

In [57]:
accidents_clean[numerical_column].describe()

,num_units,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication
count,209275.000000,209275.000000,209275.000000,209275.000000,209275.000000,209275.000000,209275.000000
mean,2.063299,0.382707,0.001859,0.038103,0.221226,0.121520,2.244019
std,0.396030,0.799720,0.047505,0.233971,0.614939,0.450884,1.241159
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
50%,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
75%,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,11.000000,21.000000,3.000000,7.000000,21.000000,15.000000,49.000000

In [38]:
accidents_clean["num_units"].describe()

count    209275.000000
mean          2.063299
std           0.396030
min           1.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          11.000000
Name: num_units, dtype: float64

In [34]:
accidents_clean[findingOutliers(accidents_clean["num_units"])]

,crash_date,traffic_control_device,weather_condition,lighting_condition,first_crash_type,trafficway_type,alignment,roadway_surface_cond,road_defect,crash_type,...,damage,prim_contributory_cause,num_units,most_severe_injury,injuries_total,injuries_fatal,injuries_incapacitating,injuries_non_incapacitating,injuries_reported_not_evident,injuries_no_indication
2,2021-12-09 10:30:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,REAR END,T-INTERSECTION,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"$501 - $1,500",FOLLOWING TOO CLOSELY,3,NO INDICATION OF INJURY,0,0,0,0,0,3
5,2023-09-06 00:59:00,NO CONTROLS,RAIN,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,WET,UNKNOWN,INJURY AND / OR TOW DUE TO CRASH,...,"$501 - $1,500",UNABLE TO DETERMINE,1,NONINCAPACITATING INJURY,2,0,0,2,0,0
10,2023-09-07 20:32:00,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,UNKNOWN,NO INJURY / DRIVE AWAY,...,"OVER $1,500",UNABLE TO DETERMINE,1,NO INDICATION OF INJURY,0,0,0,0,0,1
15,2023-08-01 23:45:00,NO CONTROLS,CLEAR,"DARKNESS, LIGHTED ROAD",SIDESWIPE OPPOSITE DIRECTION,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",IMPROPER TURNING/NO SIGNAL,4,INCAPACITATING INJURY,1,0,1,0,0,1
54,2023-09-24 19:50:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,PARKED MOTOR VEHICLE,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"OVER $1,500",UNABLE TO DETERMINE,3,NO INDICATION OF INJURY,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209236,2025-01-16 23:24:00,STOP SIGN/FLASHER,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,FOUR WAY,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,$500 OR LESS,UNDER THE INFLUENCE OF ALCOHOL/DRUGS (USE WHEN...,1,NO INDICATION OF INJURY,0,0,0,0,0,1
209247,2025-01-17 03:05:00,TRAFFIC SIGNAL,CLEAR,"DARKNESS, LIGHTED ROAD",FIXED OBJECT,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",FAILING TO REDUCE SPEED TO AVOID CRASH,1,NO INDICATION OF INJURY,0,0,0,0,0,1
209254,2025-01-17 16:04:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,DIVIDED - W/MEDIAN BARRIER,STRAIGHT AND LEVEL,DRY,NO DEFECTS,NO INJURY / DRIVE AWAY,...,"OVER $1,500",NOT APPLICABLE,3,NO INDICATION OF INJURY,0,0,0,0,0,3
209256,2025-01-17 22:51:00,TRAFFIC SIGNAL,UNKNOWN,"DARKNESS, LIGHTED ROAD",ANGLE,T-INTERSECTION,STRAIGHT AND LEVEL,WET,UNKNOWN,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",EQUIPMENT - VEHICLE CONDITION,3,NO INDICATION OF INJURY,0,0,0,0,0,3
209276,2025-01-17 16:50:00,TRAFFIC SIGNAL,CLEAR,DAYLIGHT,TURNING,NOT DIVIDED,STRAIGHT AND LEVEL,DRY,NO DEFECTS,INJURY AND / OR TOW DUE TO CRASH,...,"OVER $1,500",FAILING TO YIELD RIGHT-OF-WAY,3,NO INDICATION OF INJURY,0,0,0,0,0,3

## 5. Exploratory Data Analysis (EDA)
- Univariate distributions
- Bivariate relationships
- Correlations/associations
- Well-labeled, readable plots with units where applicable

## 6. Modeling / Deeper Analysis (if applicable)
- Define task (prediction, classification, clustering, inference, etc.)
- Train/test split or cross-validation
- Baselines, metrics, and parameter choices
- Control randomness with fixed seeds

In [27]:
cols = ['weather_condition', 'lighting_condition', 'roadway_surface_cond', 'prim_contributory_cause']
accidents_clean[cols].nunique()

weather_condition          12
lighting_condition          6
roadway_surface_cond        7
prim_contributory_cause    40
dtype: int64

## 7. Performance Evaluation and Enhancement (if applicable)

## 8. The FOUR Analytical Questions
- Answer each questions with supporting facts from the data analysis.
- Use visuals for clearer communication whenever possible.

## 9. Results & Interpretation
- Summarize key findings
- Discuss insights generated from the data analysis and modeling
- Present the most informative visuals/tables with clear captions
- Relate results back to the research questions

## 10. Conclusions & Limitations
- What did you learn?
- What are limitations and possible biases?
- What are logical next steps or improvements?

## References
- Any academic articles, blogs, or documentation used
- All references in APA format only
- Citation in text example: The field of natural language processing has become dominated by deep learning approaches (Young et al., [2018](https://doi.org/10.1109/MCI.2018.2840738)).
- Citation example in the list:
    - [Python Docs](https://docs.python.org/3/)
    - [Python Tutorial](https://docs.python.org/3/tutorial/index.html)

## Academic Integrity

- Work must be your own. If you use code snippets or ideas from references, cite them in the notebook.
- Do not include copyrighted data not permitted for redistribution.

## Plagiarism
It is fine to seek help from friends or from online resources when you do the assignment, However,
seeking help should not go overboard, to the point of getting (or even paying) someone to
complete the assignment partly or fully for you, copying from online resources without
understanding, or doing any means with the intention to cheat. 

For this assignment, plagiarism
means the following:
(a) Turning in a work that, from the examiner’s point of view, you do not sufficiently understand.
(b) Turning in someone else’s work (whether partly or fully) as your own.
(c) To use another’s work (whether partly or fully) without crediting the source.
(d) Any means of cheating.

**Plagiarism is a serious offence.**

**We will give ZERO (0) marks to students who plagiarize AND to students who intentionally or
unintentionally help other students to plagiarize by giving all or some of their code.**

## Final Self‑Checklist (before submitting)

* [ ] Rename your Jupyter Notebook file according to your group number
* [ ] All items in README section are filled up
* [ ] All group members' ID, name, and contribution fill-in.
* [ ] Dataset link is from a recognized source and publicly accessible
* [ ] YouTube link is accessible.
* [ ] Notebook runs end‑to‑end with no manual steps beyond placing data files
* [ ] Dataset loaded once only
* [ ] No absolute paths; only relative paths used
* [ ] All figures have titles/labels; text and tables are readable
* [ ] Methods and choices are explained and justified
* [ ] References properly cited
* [ ] Notebook is clear, professional, and run within reasonable runtime